### ISSUE TITLE
KNMI weather app

### ISSUE THREAD

**Issue by HanZel62** [athombv/homey-vectors-public#119]
Please provide icons for the KNMI weather app, Thnx

**Comment by IvoDerksen** [comment]
Due to copyright and to respect the usage of the governments logo, only a part of current app icon of the iOS and Android app have been made. This makes it relatable to the KNMI app, yet still is a community app.
[nl.knmi.community.zip](https://github.com/athombv/homey-vectors-public/files/6796811/nl.knmi.community.zip)
