### ISSUE TITLE
com.Coderax.MillHeating

### ISSUE THREAD

**Issue by Coderaxx** [athombv/homey-vectors-public#202]
Hi!🙂

Since I'm asking here, my design skills are obviously not great😅

I need an icon for the driver Mill-sense. Is that something we could make happen?😁

Image of the Mill Sense: ![image](https://github.com/athombv/homey-vectors-public/assets/48462275/307184f1-2ed1-45bc-9a7d-c9f2d1818b20)

As the sensor is mostly covered in white paint, I think the best would solution would be to outline the white, and fill with black. Probably also a good idea to add some white spacing between the top and sides to easily identify? You're the expert, so I'll leave this up to you.😉

Thanks!

Best
Jesper

**Comment by IvoDerksen** [comment]
Thanks Jesper! I'll have a look :)

**Comment by IvoDerksen** [comment]
Here you go!

**Comment by IvoDerksen** [comment]
Is this to your liking?

I've placed it in a way that it is 'facing' you. A style I incorporate in all icons since last year. The use of black is minimised.

These were my options
<img width="566" alt="image" src="https://github.com/athombv/homey-vectors-public/assets/22196684/256fb982-08f0-4358-99d1-d7b7c82ea99c">

**Comment by IvoDerksen** [comment]
now you have the two options available :)
https://github.com/athombv/homey-vectors-public/commit/b0f8a3a9a3973821a2840181027f4885dd056a90
