### ISSUE TITLE
Icons in new format for Zooz products

### ISSUE THREAD

**Issue by koktaildotcom** [athombv/homey-vectors-public#216]
Hi Ivo,

Can you convert these icons to the new format? And can you explain what the standards are for the icons for future references?

This is the full list that I currently use: [drivers.zip](https://github.com/athombv/homey-vectors-public/files/13248982/drivers.zip)

ZEN14
ZEN71
ZSE29
ZEN76
ZEN51
ZEN31
ZEN77
ZEN30
ZEN16
ZEN34
ZSE18
ZEN72
ZEN52
ZSE42
ZEN32
ZSE11
ZSE44
ZSE41
ZSE43
ZEN17

**Comment by IvoDerksen** [comment]
Hey!
I wanted to start with a compliment!
Very nice job already!

Next a few hints and tips and tricks for the next time:
**Black and transparant(not white!)**
This won't work, it wil be a block if you're lucky, and sometimes ruined the whole svg due to clipping masks.
![image](https://github.com/athombv/homey-vectors-public/assets/22196684/a1deff60-85f8-4651-b332-76f2981272da)

**Keep it simple**
![image](https://github.com/athombv/homey-vectors-public/assets/22196684/89c1ec57-f7a2-40c5-847a-ff82c76a7406) remove these details, you can't see them, unless it is a pairing icon (a bigger page)

**Keep it friendly** 
while this sounds crazy, the effects in the app are (Left to right biased, I admit) nice when we look into the device
![image](https://github.com/athombv/homey-vectors-public/assets/22196684/378f5eb9-c19d-4971-acca-d025160899cc)

**Outline them devices**
ZSH 43 Example, make the outlines thicker (I use outlines 960 - 40pt and details 20pt)
![image](https://github.com/athombv/homey-vectors-public/assets/22196684/9260050b-8c89-48fe-9281-16e79d12f6ab)

**Comment by IvoDerksen** [comment]
I had a plan to do them this weekend, but I was a bit delayed! So I'm going at them today and tomorrow :)

**Comment by koktaildotcom** [comment]
Thank you for your comments and guidelines. I will keep that in mind next time.

**Comment by IvoDerksen** [comment]
Got 2 more to go!

**Comment by IvoDerksen** [comment]
Hey!
I've finished them!
[zooz.zip](https://github.com/athombv/homey-vectors-public/files/13312456/zooz.zip)

**Comment by koktaildotnl** [comment]
Wooow they are looking so nice! Thank you so much 🙏🏻. I just added them to the app but I am still missing one for Outdoor double plug (ZEN14).

**Comment by IvoDerksen** [comment]
Oh that slipped my attention! Well tonight you'll have em!
And thanks!

**Comment by koktaildotnl** [comment]
Thank you!

**Comment by IvoDerksen** [comment]
And with the outdoor plug.
For simplicity I removed the caps at the top, but now you're complete. 
And well done on finishing the app!

[zooz.zip](https://github.com/athombv/homey-vectors-public/files/13321831/zooz.zip)

**Comment by koktaildotnl** [comment]
Looking good 🔥.  Thank you so much!
