### ISSUE TITLE
com.amazon.alexa

### ISSUE THREAD

**Issue by hive** [athombv/homey-vectors-public#50]
Hey Ivo!

Got a new one for you, i've made an app which allows Homey to make Alexa do stuff - say the weather, traffic, news, text to speech and I was wondering if it would be possible to get five icons to start with. 

- Echo Spot :: https://www.amazon.com/Echo-Spot-Smart-Display-Alexa/dp/B073SQYXTW 
- Echo Plus (1st Gen) :: https://www.amazon.com.au/Echo-Plus-1st-Gen-built/dp/B077T7Y9FV
-  Echo (2nd Gen) :: https://www.amazon.com.au/dp/B078GTRR5L/ref=fs_rad 
- Echo Dot (2nd Gen) :: https://www.officeworks.com.au/shop/officeworks/p/amazon-echo-dot-2nd-gen-black-syamzdotbk
- Fire HD (10) :: https://www.amazon.com/Amazon-Fire-HD-10-10-Inch-Tablet-16GB-Black/dp/B00VKIY9RG

**Comment by IvoDerksen** [comment]
Here you go!

**Comment by Jamie-Peake** [comment]
Hey Ivo, 

Amazing work as usual, from your work i've been able to build out all 9 echo devices, except the Echo Show v1 and v2. 

https://cdn.pocket-lint.com/r/s/970x/assets/images/145813-smart-home-vs-amazon-echo-show-2018-vs-amazon-echo-show-2017-whats-the-difference-image1-lejf2ydnpm.jpg?v1

I would appreciate your help,

Thanks

**Comment by IvoDerksen** [comment]
Hey Jamie, thanks!
Do you also want an icon for the Echo Sub?

**Comment by hive** [comment]
That would be great!

Thanks

**Comment by IvoDerksen** [comment]
They're all finished!

**Comment by hive** [comment]
Thanks Ivo!

**Comment by Jamie-Peake** [comment]
Hey Ivo, I am looking to add support for the Sonos One and Sonos Beam

https://content.sonos.com/cdn_static/on/demandware.static/-/Sites-sonos-master/default/dwbe04506e/images/one/one-feature.png

**Comment by IvoDerksen** [comment]
I'll check at HQ, since the Sonos app is Athom controlled, so those icons fall under a policy, but I think it's no problem. 
Plus I like the idea of adding the logo to the device. 
I'm thinking of making it a capability like icon placing it in the right bottom corner, with a better (show you in a sec). So I'll show you what I mean, and then you can decide!

**Comment by IvoDerksen** [comment]
Hey Jamie, the policy is that we cannot cause problems due to multiple apps for the same device, due to confusion.
However I've been given the green light to give you the icons.

The alteration is the echo logo on them
You can use the echo_brand and place it in the right bottom corner (I'd also suggest you to do that to the ecobee logo).
