### ISSUE TITLE
Alexa Device Updates

### ISSUE THREAD

**Issue by hive** [athombv/homey-vectors-public#84]
Hey Ivo, 

I am looking to add some of the new devices to the Alexa app : https://github.com/athombv/homey-vectors-public/tree/master/com.amazon.alexa

Would it please be possible to get an icon for 

 - The Echo Studio https://www.amazon.com/dp/B0849HZ86Y?ref=MarsFS_AUCC_oe
 - The Echo Flex https://www.amazon.com/Echo-Flex/dp/B07MLY3JKV
 - The Echo Dot with clock : https://images-na.ssl-images-amazon.com/images/I/51EI3CbMQhL._AC_SL1000_.jpg
 - The echo show 5 https://www.amazon.com.au/Echo-Show-5-Compact-smart-display-with-Alexa-Black/dp/B07KD7TJD8
 - The echo show 8 https://www.amazon.com.au/dp/B07W16XS74?ref=MarsFS_AUCC_cn

Much appreciated!

**Comment by IvoDerksen** [comment]
Hey! 
I've created the icons.

For the clock I've chosen not to add the time, since it's dynamic (just as the thermostat), can be confusing to see. Therefor removing that is preferred and keeps it simple.

The new boldness of the icons has been added. I can image this is a contrast, therefore I'll try to update them the coming week (if you agree). It removes some details, but adds the boldness and better usability for flow. 

I'll not close the issue until I've done that!

**Comment by hive** [comment]
Hey Ivo, 

Thank you for doing that, I am happy with what every you recommend in regards to boldness, (though I also like the detailed ones). I hope its not to much trouble bringing all of the icons to have the same look/feel. There are a few of them now (17). I've attached them all to make it a bit easier. 


[Icons.zip](https://github.com/athombv/homey-vectors-public/files/4720460/Icons.zip)

**Comment by IvoDerksen** [comment]
Thanks!

**Comment by IvoDerksen** [comment]
Here you go! I've just seen the sonos 1, ecobee, gigaset and netgear have to be done still.

**Comment by IvoDerksen** [comment]
And the last ones!
